### ISSUE TITLE
hdfs write failed

### ISSUE THREAD

**Issue by yetingsky** [Tencent/plato#55]
check output stream failed https://github.com/Tencent/plato/blob/master/plato/util/foutput.cc#L125.

**Comment by yetingsky** [comment]
```
hdfsWrite: FSDataOutputStream#write error:
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.apache.hadoop.net.SocketInputStream$Reader.performIO(SocketInputStream.java:57)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2275)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.transfer(DFSOutputStream.java:1288)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:1256)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1401)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.processDatanodeError(DFSOutputStream.java:1148)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:645)
F1224 20:49:20.947154 228281 foutput.cc:116] Check failed: fs_->os_.good() flush file filed, filename: 
```

**Comment by yetingsky** [comment]
After dig into HDFS c++ client code，we suspect HDFS client raise an exception and make boost `filtering_stream` broken。

**Comment by xuguruogu** [comment]
Normally speaking, fault tolerant with code is not best practice. We suggest simply restart the task and report warning on several failure.

**Comment by yetingsky** [comment]
What do mean restart task? restart whole plato job or just retry HDFS write phase?

**Comment by xuguruogu** [comment]
> What do mean restart task? restart whole plato job or just retry HDFS write phase?

Actually I am not sure if retry hdfs_write can solve this problem. Due to my experience, HDFS client has already tried to recover from hdfs nemanode/datanode failure, an exception thrown to upper code mostly means we can do nothing with it in the near future.
